### ISSUE TITLE
Update readme.md

### ISSUE THREAD

**Issue by ng29** [SwitchbladeBot/invidget#27]
@pedrofracassi 

In the  README.MD light theme preview image is showing 404 error after clicking it. 

So can fix it up 👍

**Comment by pedrofracassi** [comment]
It seems to work fine on my end. Could you let me know if this is still happening?

**Comment by ng29** [comment]
> It seems to work fine on my end. Could you let me know if this is still happening?

It does not shows 4040 now but this error message

```
error on line 1 at column 39303: AttValue: ' expected

```

**Comment by pedrofracassi** [comment]
That's weird and doesn't sound like an error on our end at all. Could you show me a screenshot?

**Comment by ng29** [comment]
> That's weird and doesn't sound like an error on our end at all. Could you show me a screenshot?
 I reckon that cant share ss here..

**Comment by pedrofracassi** [comment]
It sound like a problem with your browser not being able to read the SVG XML correctly for some reason. What browser and OS are you on?

**Comment by ng29** [comment]
> It sounds like a problem with your browser not being able to read the SVG XML correctly for some reason. What browser and OS are you on?

ohh, no idea about that.. Chrome +Macos

**Comment by pedrofracassi** [comment]
Weird... Please share a screenshot if possible, it would help a lot. You can just Command + V an image into the GitHub text box.

**Comment by ng29** [comment]
![image](https://user-images.githubusercontent.com/26463272/96590459-ad677400-1303-11eb-8fe2-7df6f6cacadc.png)

**Comment by pedrofracassi** [comment]
You. Browser error it seems. Had never encountered it. Will take a look.

**Comment by CloudGruber** [comment]
All links seem to be down actually.

**Comment by jaxxibae** [comment]
I'll try to look into it and reproduce it when I get home

**Comment by Doges** [comment]
invidget itself is down i think. lemme turn it on

**Comment by CloudGruber** [comment]
Still down for me, it seems.

**Comment by Doges** [comment]
it working now @CloudGruber , closing the issue.
