### ISSUE TITLE
Renew the domain

### ISSUE THREAD

**Issue by OMEGA6405** [SwitchbladeBot/invidget#74]
Your domain is offline

**Comment by Doges** [comment]
Working on it

**Comment by OMEGA6405** [comment]
Okay

**Comment by kafumanto** [comment]
Hi! Just to know how to act since 2 weeks passed, will this issue be fixed or the service will remain definitely offline? Thanks.

**Comment by Doges** [comment]
> Hi! Just to know how to act since 2 weeks passed, will this issue be fixed or the service will remain definitely offline? Thanks.

Hey! I tried to renew it but namecheap is not letting me do it, I'm waiting their reply to try it again.

Thanks!

**Comment by Doges** [comment]
It works now

**Comment by OMEGA6405** [comment]
yay!
